FROM rust:1.44 as builder
WORKDIR /usr/src/codedetection-telegram
ARG CODEDETECTION_SOURCE_URL=https://github.com/ZaMaZaN4iK/codedetection-telegram.git
RUN git clone ${CODEDETECTION_SOURCE_URL}
WORKDIR codetection-telegram
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates
COPY --from=builder /usr/local/cargo/bin/codedetection-telegram /usr/local/bin/codedetection-telegram
CMD ["codedetection-telegram"]