FROM rust:1.45.2 as builder
WORKDIR /usr/src/codedetection-telegram
COPY . .
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && aplt-get clean
COPY --from=builder /usr/local/cargo/bin/codedetection-telegram /usr/local/bin/codedetection-telegram
CMD ["codedetection-telegram"]