FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

ARG CODEDETECTION_VERSION=1.0.0

ARG CODEDETECTION_SOURCE_URL=https://github.com/ZaMaZaN4iK/codedetection-telegram/archive/v${CODEDETECTION_VERSION}.zip

RUN dnf install -y ca-certificates perl autoconf automake libtool wget unzip clang cmake make python3-pip \
    && pip install conan

WORKDIR /usr/src/codedetection-telegram

RUN wget ${CODEDETECTION_SOURCE_URL} && unzip v${CODEDETECTION_VERSION}.zip

WORKDIR codedetection-telegram-${CODEDETECTION_VERSION}

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/codedetection-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/codedetection_telegram"]

