FROM fedora:latest

LABEL maintainer="Alexander Zaitsev <zamazan4ik@tut.by>"

ARG CODEDETECTION_SOURCE_URL=https://github.com/ZaMaZaN4iK/codedetection-telegram.git

RUN dnf install -y ca-certificates perl autoconf automake libtool clang cmake make git python3-pip \
    && pip install conan

WORKDIR /usr/src/codedetection-telegram

RUN git clone ${CODEDETECTION_SOURCE_URL}

WORKDIR codetection-telegram

RUN CC=clang CXX=clang++ cmake -B build -DCMAKE_BUILD_TYPE=Release && \
    cmake --build build --target install && \
    rm -rf /usr/src/codedetection-telegram

WORKDIR /usr/local/bin

ENTRYPOINT ["/usr/local/bin/codedetection_telegram"]

