FROM rust:1.45.2 as builder
WORKDIR /usr/src/codedetection-telegram
ARG CODEDETECTION_SOURCE_URL=https://github.com/ZaMaZaN4iK/codedetection-telegram.git
ARG CACHE_DATE=2020-01-01
RUN git clone --single-branch --branch master ${CODEDETECTION_SOURCE_URL}
WORKDIR codedetection-telegram
RUN cargo install --path .

FROM debian:buster-slim
RUN apt-get update && apt-get install -y openssl ca-certificates && apt-get clean
COPY --from=builder /usr/local/cargo/bin/codedetection-telegram /usr/local/bin/codedetection-telegram
CMD ["codedetection-telegram"]
